# Generated by Django 5.1.1 on 2024-09-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CandidateApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("contact_1", models.CharField(max_length=20)),
                ("contact_2", models.CharField(blank=True, max_length=20, null=True)),
                ("email_1", models.EmailField(max_length=254)),
                ("email_2", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Pakistan", "Pakistan"),
                            ("India", "India"),
                            ("United States", "United States"),
                            ("Canada", "Canada"),
                        ],
                        max_length=50,
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("job_id", models.CharField(max_length=50)),
                ("candidate_id", models.CharField(max_length=50)),
                ("job_title", models.CharField(max_length=100)),
                ("calling_date", models.DateField()),
                ("calling_time", models.TimeField()),
                (
                    "timezone",
                    models.CharField(
                        choices=[("CST", "CST"), ("PST", "PST"), ("EST", "EST")],
                        max_length=3,
                    ),
                ),
                (
                    "recruitment_source",
                    models.CharField(
                        choices=[
                            ("Indeed", "Indeed"),
                            ("LinkedIn", "LinkedIn"),
                            ("Monster", "Monster"),
                            ("Dice", "Dice"),
                            ("Taldel", "Taldel"),
                            ("traxccel", "traxccel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("second_interview_date", models.DateField(blank=True, null=True)),
                ("second_interview_time", models.TimeField(blank=True, null=True)),
                (
                    "second_interview_timezone",
                    models.CharField(
                        blank=True,
                        choices=[("CST", "CST"), ("PST", "PST"), ("EST", "EST")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("hiring_manager_id", models.CharField(max_length=50)),
                ("interviewer_id", models.CharField(max_length=50)),
                ("interview_duration", models.PositiveIntegerField()),
                (
                    "interview_mode",
                    models.CharField(
                        choices=[("In-Person", "In-Person"), ("Virtual", "Virtual")],
                        max_length=10,
                    ),
                ),
                (
                    "technical_score",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                ("technical_assessment_score", models.PositiveIntegerField()),
                (
                    "leadership_potential",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                        ]
                    ),
                ),
                (
                    "recommend",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=3
                    ),
                ),
                ("interview_panel", models.TextField()),
                ("interview_feedback", models.TextField()),
                (
                    "overall_technical_rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                (
                    "overall_personality",
                    models.CharField(
                        choices=[
                            ("Extrovert", "Extrovert"),
                            ("Introvert", "Introvert"),
                            ("Ambivert", "Ambivert"),
                            ("Assertive", "Assertive"),
                            ("Reserved", "Reserved"),
                            ("Creative", "Creative"),
                            ("Analytical", "Analytical"),
                            ("Proactive", "Proactive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "communication_skills_score",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                (
                    "problem_solving_skills",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                        ]
                    ),
                ),
                (
                    "team_collaboration_experience",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                        ]
                    ),
                ),
                (
                    "current_employment_status",
                    models.CharField(
                        choices=[
                            ("Fresh", "Fresh"),
                            ("Employed", "Employed"),
                            ("Unemployed", "Unemployed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("follow_up_actions", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="ApplicationForm",
        ),
    ]
