# Generated by Django 5.1.1 on 2024-09-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("form_app", "0002_candidateapplication_delete_applicationform"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("key_client_id", models.AutoField(primary_key=True, serialize=False)),
                ("client_name", models.CharField(max_length=255)),
                ("client_type", models.CharField(max_length=100)),
                ("client_location", models.CharField(max_length=255)),
                ("client_state_country", models.CharField(max_length=100)),
                ("client_contact", models.CharField(max_length=100)),
                ("client_business", models.CharField(max_length=100)),
                ("primary_contact_email", models.EmailField(max_length=254)),
                (
                    "secondary_contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("primary_contact_num", models.CharField(max_length=20)),
                (
                    "secondary_contact_num",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("date_of_contract", models.DateField()),
                ("expiry_of_contract", models.DateField()),
                ("status", models.CharField(max_length=50)),
                ("fee_structure", models.TextField()),
                ("time_stamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="CandidateApplication",
        ),
    ]
